---
name: Build manifest
inputs:
  target:
    required: true
  dockerhub_username:
    required: true
  dockerhub_password:
    required: true
runs:
  using: composite
  steps:
    - name: Set up TARGET
      run: echo "TARGET=${{ inputs.target }}" | tee $GITHUB_ENV
      shell: bash
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_password }}
    - name: Push manifests
      shell: bash
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
      run: ./deploy-manifests.sh
